travis:
  secure:
    BINSTAR_TOKEN: BLIWw/ksQbMKUpw/ZhR3KXrJ3qVqnsAoEsxy1Wr5LRoJ0QOaIIgZAMjSVYW/fqJUivNrPYpMYIOKVui/U1tiz+V7bm8qPA0QBo+4FALyieVVQnB4+c4AtpEegufers8OPkhoUXWG094VsW1r2LVAgExFcSOPZiaPQIwCtvUERqSeH9FeLyKyk4OSoAc8bkrAeT8qZv+2Ae3+WDEsk1F/sphnJNTraYRltRRBsJE2c6NMbl5v5/LEV9cOpNCO1VLPwi2QlSWd5p0kIyi/rMm4NWQDMlYUnfPFvMUD6ieaEHXl5ghoihqkLV+DqHV75V9p0+Ltbk6PUaGdSFOpN5Uwd5KopcR0M4MnrRTBUODu0xWwBO34uLosTN6mCcOcD4gmDnXF6NPtyiceqA16w3AUmOunRwhjWnGjXyuy7vdclyS1zW1EtDNp4jc8r5R5BmGKcyD+oSKWpsUGQVIteVlcglyMRmU1LfbDZKHYb160+aHT5FruPzSKKKZ4JXAY+a7WGgi0sw+TbLaUX8lncJldMMg1CIdKBw7iKOFygK9Ju65hzBSJzQeqBfpPkTj3PMnqvFphFlVJZvM/yixczTjZNWP4Cy/bTEtgDpU19sCEQ+he45HXzGUhiKCgyagTGb7Bz8lBGukTAQcmVNB7ZmuJmQZtlqE3DGgczkb0G2m8GqU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
