travis:
  secure:
    BINSTAR_TOKEN: cc/g70jMp5mFscGxNwzCy4lv4krCvlQEOhCLqABMKW8KBOyRt7n5jaWXNdkJYOj51GkLWTeWR+d4HL9Mk5xQiaRlbmRg264uNjz6PEB2WJ6Pgq5DbUUzpMEnpHE2rVFh/M43oJ1GDAAAoREOU3APRMNFIpa/l+NebrT/AeKkDsdRMCMuWywkkp+16jLz2MNw34wjtXDmbp0/FKjGTj4ltDiBJqMMReK5rk/+r60koURc07CpJdo/5HrOkOHb42xyXYD4O0nRJuIdYvxGpGkpPPK5iZ9UrO0Oh9AoevFIlR8xLblTPil0CmKl6kMjkZc8XOorMzv18/BYXt/l+uKJHyGxh3fHTzeyTYBy80dqSSrBFreAn7SPsaHW14aJM1JcOSRVLOCCpuhgDXvSP210G7pzyofLtOsvZqBfD3zvPhe7V/CgfsUOIjw3IMgoKr6kcl3VIbcd3BpCi6faPMq/G8InFSVRfGlspYlpJfwHQHzesyANEowZ97vw5KHDL8Ia6KW+gJXWwAMEN7hJlUD9TmRZZVFxawO/xMAjH3RRpWOk9eMu4owCrivW1rvA0ShLJtH92ee2kJK2WOpTyFIwd6AceIGYDyo1IOKc3GtdaTs7IXaPmYXTW6h3ZPYy79b/CnvVqtF+X8537JCbXvlmo9rcukfBXjp/2DYvA1CJvQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
